Readme updated
TaskarCenterAtUW/TDEI-auth-n-z pull request #62
Opened 2023-05-31 09:40 UTC by MashB

Readme updated based on review feedback

2023-05-31 10:58 UTC, susrisha requested changes
Two minor changes

2023-05-31 10:58 UTC, susrisha commented on README.md
> +Secrets are configured as an environment variables on the deployment server.
Remove `an` . The sentence should be
Secrets are configured as environment variables on the deployment server.

2023-05-31 12:06 UTC, rdevalap reviewed
Is the URL at the bottom correct?
https://tdei-gateway.azurewebsites.net/swagger-ui/index.html?

2023-05-31 12:06 UTC, rdevalap commented on README.md
> +- `Gateway` service is first point of contact for clients. Every request to gateway is Authenticated & Authorized
`Gateway` service is **the** first point of contact

2023-05-31 12:06 UTC, rdevalap commented on README.md
> +- For Authentication, `Auth Service` will interact with `Keycloak Service` for verification.
For Authentication, `Auth Service` interacts with `Keycloak` for verification. Please write it in "present tense".

2023-05-31 12:06 UTC, rdevalap commented on README.md
> +    - Successful authentication auth service will return with access_token & refresh_token as a response to requests.
Same here, 
On successful authentication, auth service returns _access_token_ & _refresh_token_ as response

2023-05-31 12:06 UTC, rdevalap commented on README.md
> +- For Authorization, `Auth Service` will interact directly with `TDEI Database`. `TDEI Database` maintains the user
For Authorization, Service interacts directly with `TDEI Database`

2023-05-31 12:54 UTC, rdevalap approved these changes

2023-06-01 10:33 UTC, susrisha approved these changes

2023-06-01 10:35 UTC, merged